services:
  - type: web
    name: hms-server
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: hms-client
    env: node
    plan: free
    rootDir: client
    # Using more memory and ignoring lint errors for faster build
    buildCommand: npm install && NODE_OPTIONS=--max-old-space-size=1024 npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: hms-server
          type: web
          property: host
